name: Deploy to AWS Lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1

      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Lambda Build & Update
        run: |
          pip3 install awscli
          cd lambda && zip -r package.zip ./*
          aws lambda update-function-code --function-name kuinfo2019slack --zip-file fileb://package.zip --publish
          
      - name: EventBridge Settings cron
        run: |
          aws events put-rule --name every60minutes_0 --schedule-expression "cron(0 * * * ? *)"